{% set name = "alfa" %}
{% set version = "1.1.1" %}

package:
  name: alfa
  version: "1.1.1"

source:
  url: https://files.pythonhosted.org/packages/86/29/0fbb3cb7b5cfb9ae53ffff72e846e2c99dfb0321f5b14637ee2d71506249/alfa-1.1.1.tar.gz
  sha256: a2ce74e4140994992b22f590e0511c4a61af57095718d13754647a3a8a6fbcfc

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - alfa = alfa:main

requirements:
  host:
    - matplotlib
    - numpy
    - pip
    - progressbar2
    - pybedtools
    - pysam
    - python
  run:
    - matplotlib
    - numpy
    - progressbar2
    - pybedtools
    - pysam
    - python

about:
  home: https://github.com/biocompibens/ALFA
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A simple software to get a quick overview of features composing NGS dataset(s).
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - mbahin
