{% set name = "alfa" %}
{% set version = "1.0.6" %}

package:
  name: alfa
  version: "1.0.6"

source:
  url: https://files.pythonhosted.org/packages/a1/f0/d51f25b48645fc0b4784b5d36fe7b6d6aebe1d9c1be58747196c457e3e1c/alfa-1.0.6.tar.gz 
  sha256: 628fa47efdd4ca2af7434c2ffa81a00bca237d024421b092087ba45379299c32

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - alfa = alfa:main

requirements:
  host:
    - matplotlib
    - numpy
    - pip
    - progressbar2
    - pybedtools
    - pysam
    - python ==3.6
  run:
    - matplotlib
    - numpy
    - progressbar2
    - pybedtools
    - pysam
    - python ==3.6

about:
  home: https://github.com/biocompibens/alfa
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A simple software to get a quick overview of features composing NGS dataset(s).
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - mbahin
