{% set name = "ALFA" %}
{% set version = "0.27.4" %}

package:
  name: alfa
  version: "0.27.4"

source:
  url: https://test-files.pythonhosted.org/packages/d4/e3/e442f705f1601a7b90705510efd36d69cd911213f8a61e7be9b81b427e51/ALFA-0.27.4.tar.gz
  sha256: 65634e26c7b29f9887910477d024c3cd5315a86932627da8d8803135bcb96084

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - ALFA = ALFA:main

requirements:
  host:
    - matplotlib
    - numpy
    - pip
    - progressbar2
    - pybedtools
    - pysam
    - python ==3.6
  run:
    - matplotlib
    - numpy
    - progressbar2
    - pybedtools
    - pysam
    - python ==3.6

about:
  home: https://github.com/biocompibens/ALFA
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A simple software to get a quick overview of features composing NGS dataset(s).
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - mbahin
