{% set name = "ALFA" %}
{% set version = "1.0.0" %}

package:
  name: alfa
  version: "1.0.0"

source:
  url: https://files.pythonhosted.org/packages/68/6c/a10e7bd755a0ee1f1ef998c6275b74efef7bf8eddea1658648a0f4dbb0a4/ALFA-1.0.0.tar.gz
  sha256: 17051c2bab51ea6a562ddcb8e4651207f6d4e67d0eaeabdcbd4842e19fb272c8

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - ALFA = ALFA:main

requirements:
  host:
    - matplotlib
    - numpy
    - pip
    - progressbar2
    - pybedtools
    - pysam
    - python ==3.6
  run:
    - matplotlib
    - numpy
    - progressbar2
    - pybedtools
    - pysam
    - python ==3.6

about:
  home: https://github.com/biocompibens/ALFA
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A simple software to get a quick overview of features composing NGS dataset(s).
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - mbahin
